---
title: "MAplots_fig3"
author:
- name: Nikita Verheyden
  affiliation: JLU Giessen
  date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
      toc: TRUE
      toc_float: TRUE
      code_folding: hide

header-includes:
- \makeatletter\renewcommand*{\fps@figure}{h}\makeatother
- \usepackage{placeins}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


dir
```{r dir}
setwd("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/02_MAplots")
```

## packages 
```{r packages}

source("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/themes/theme_paper.R")
library(readxl)
library(ggplot2)
library(ggrastr)
library(dplyr)
library(MASS)
library(ggpubr)
library(ggrepel)
```

## data
```{r data}
#Ribo profiling
RNA <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/01_Ribosome_profiling_pipeline/RNA_masterframe.csv")
RPF <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/01_Ribosome_profiling_pipeline/RPF_masterframe.csv")

#Translational efficiency
TEframe <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/deltaTE/TE_m23_genesInRNAandRPF.csv")
head(TEframe)

#targets
larget <- readRDS("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure2/02_compare_miR_enriched_to_Ago_binding_sites/mir181_bs.rds")
largetframe <- as.data.frame(larget)
table(largetframe$set)
largetframe <- largetframe[!(largetframe$set == "ago_bs_mir181_chi"),]
```
## colours
```{r colours}
#colours
farbeneg <- "#b4b4b4"
farbe1 <- "#0073C2FF"
farbe2 <- "#EFC000FF"
farbe3 <- "#CD534CFF"
farbe4 <- "#7AA6DCFF"
farbe5 <- "#868686FF"
farbe6 <- "#003C67FF"
farbe7 <- "#8F7700FF"
farbe8 <- "#3B3B3BFF"
farbe9 <- "#A73030FF"
farbe10 <- "#4A6990FF"
farbe11 <- "#FF6F00FF"
farbe12 <- "#C71000FF"
farbe13 <- "#008EA0FF"
farbe14 <- "#8A4198FF"
farbe15 <- "#5A9599FF"
farbe16 <- "#FF6348FF"
  
RNApcol <- "#b56504"
RNAncol <- "#027d73"
RPFpcol <- "#c4c404"
RPFncol <- "#8d0391"
```




# genelist
```{r genelist}
Agenes <- c("Cd69", "Dusp6", "Ptpn22", "Zfp36l1", "Zfp36l2")
Ogenes <- c("Cd69", "Dusp6", "Ptpn22")
Ngenes <- c("Zfp36l1", "Zfp36l2")
```


# MA plots with labels
```{r plotslab}
ylim <- 2
xlim <- 10^6
xmin <- 10

lfcsig <- 0
pvsig <- 0.05

#RNA
RNA$LFCandPADJSig <- "Not significant"
RNA$LFCandPADJSig[RNA$padj <= pvsig & RNA$log2FoldChange >= lfcsig] <- "Significant up"
RNA$LFCandPADJSig[RNA$padj <= pvsig & RNA$log2FoldChange <= -lfcsig] <- "Significant down"

#make columns with identifiers
RNAdat <- RNA[RNA$baseMean >= xmin,]
RNAdat$ycutoff <- "in"
RNAdat$ycutoff[RNAdat$log2FoldChange > ylim] <- "high"
RNAdat$ycutoff[RNAdat$log2FoldChange < -ylim] <- "low"

RNAdat$xcutoff <- "in"
RNAdat$xcutoff[RNAdat$baseMean > xlim] <- "high"

#implement cutoff
RNAdat$log2FoldChange[RNAdat$log2FoldChange > ylim] <- ylim
RNAdat$log2FoldChange[RNAdat$log2FoldChange < -ylim] <- -ylim
RNAdat$baseMean[RNAdat$baseMean > xlim] <- xlim


#RPF
RPF$LFCandPADJSig <- "Not significant"
RPF$LFCandPADJSig[RPF$padj <= pvsig & RPF$log2FoldChange >= lfcsig] <- "Significant up"
RPF$LFCandPADJSig[RPF$padj <= pvsig & RPF$log2FoldChange <= -lfcsig] <- "Significant down"


#make columns with identifiers
RPFdat <- RPF[RPF$baseMean >= xmin,]
RPFdat$ycutoff <- "in"
RPFdat$ycutoff[RPFdat$log2FoldChange > ylim] <- "high"
RPFdat$ycutoff[RPFdat$log2FoldChange < -ylim] <- "low"

RPFdat$xcutoff <- "in"
RPFdat$xcutoff[RPFdat$baseMean > xlim] <- "high"

#implement cutoff
RPFdat$log2FoldChange[RPFdat$log2FoldChange > ylim] <- ylim
RPFdat$log2FoldChange[RPFdat$log2FoldChange < -ylim] <- -ylim
RPFdat$baseMean[RPFdat$baseMean > xlim] <- xlim


#RNA
RNAmalab <- ggplot(RNAdat[!(RNAdat$xcutoff == "high"),], aes(y=log2FoldChange, x=log10(baseMean))) + geom_point_rast(shape=21, size = 0.5, 
     aes(fill = factor(LFCandPADJSig), colour=factor(LFCandPADJSig))) +
  scale_fill_manual(values = c(farbeneg, RNAncol, RNApcol)) + scale_colour_manual(values = c(farbeneg, "black", "black")) +
  geom_point(data=RNAdat[RNAdat$LFCandPADJSig == "Significant down" & RNAdat$ycutoff =="in" & RNAdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 1, colour="black", fill=RNAncol) +
  geom_point(data=RNAdat[RNAdat$LFCandPADJSig == "Significant up" & RNAdat$ycutoff =="in" & RNAdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 1, colour="black", fill=RNApcol) +
  geom_point(data=RNAdat[RNAdat$LFCandPADJSig == "Significant up" & RNAdat$ycutoff =="high" & RNAdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=24, size = 1, colour="black", fill=RNApcol) +
  geom_point(data=RNAdat[RNAdat$LFCandPADJSig == "Significant down" & RNAdat$ycutoff =="low" & RNAdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=25, size = 1, colour="black", fill=RNAncol) +
  theme_paper() +
  geom_point(data=RNAdat[RNAdat$xcutoff == "high",], aes(y=log2FoldChange, x=log10(baseMean)), shape="\u25BA", size = 3, colour=farbeneg) +
  geom_hline(yintercept = 0, linetype="solid", colour="black") + 
  geom_hline(yintercept = lfcsig, linetype="dashed", colour="black") + 
  geom_hline(yintercept = -lfcsig, linetype="dashed", colour="black") + 
  scale_y_continuous("Fold change miR-181a/b-1 KO/WT (log2)", limits = c(-ylim, ylim)) + scale_x_continuous("Base mean expression ratio (log10)", limits = c(log10(xmin), log10(xlim))) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  geom_point(data=RNAdat[RNAdat$gene_symbol %in% Ogenes,], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 2, colour="black", fill="#595959") +
  geom_point(data=RNAdat[RNAdat$gene_symbol %in% Ngenes,], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 2, colour="black", fill=farbe1) +
  geom_text_repel(data=RNAdat[RNAdat$gene_symbol %in% Agenes,], aes(label = gene_symbol),size = 3) + 
  ggtitle("RNAseq")

RNAmalab

pdf("MAplot_RNA_lab.pdf", width = 1.5, height = 1.8)
RNAmalab
dev.off()



#RPF
RPFmalab <- ggplot(RPFdat[!(RPFdat$xcutoff == "high"),], aes(y=log2FoldChange, x=log10(baseMean))) + geom_point_rast(shape=21, size = 0.5, 
     aes(fill = factor(LFCandPADJSig), colour=factor(LFCandPADJSig))) +
  scale_fill_manual(values = c(farbeneg, RNAncol, RNApcol)) + scale_colour_manual(values = c(farbeneg, "black", "black")) +
  geom_point(data=RPFdat[RPFdat$LFCandPADJSig == "Significant down" & RPFdat$ycutoff =="in" & RPFdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 1, colour="black", fill=RNAncol) +
  geom_point(data=RPFdat[RPFdat$LFCandPADJSig == "Significant up" & RPFdat$ycutoff =="in" & RPFdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 1, colour="black", fill=RNApcol) +
  geom_point(data=RPFdat[RPFdat$LFCandPADJSig == "Significant up" & RPFdat$ycutoff =="high" & RPFdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=24, size = 1, colour="black", fill=RNApcol) +
  geom_point(data=RPFdat[RPFdat$LFCandPADJSig == "Significant down" & RPFdat$ycutoff =="low" & RPFdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=25, size = 1, colour="black", fill=RNAncol) +
  theme_paper() +
  geom_point(data=RPFdat[RPFdat$xcutoff == "high",], aes(y=log2FoldChange, x=log10(baseMean)), shape="\u25BA", size = 3, colour=farbeneg) +
  geom_hline(yintercept = 0, linetype="solid", colour="black") + 
  geom_hline(yintercept = lfcsig, linetype="dashed", colour="black") + 
  geom_hline(yintercept = -lfcsig, linetype="dashed", colour="black") + 
  scale_y_continuous("Fold change miR-181a/b-1 KO/WT (log2)", limits = c(-ylim, ylim)) + scale_x_continuous("Base mean expression ratio (log10)", limits = c(log10(xmin), log10(xlim))) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  geom_point(data=RPFdat[RPFdat$gene_symbol %in% Ogenes,], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 2, colour="black", fill="#595959") +
  geom_point(data=RPFdat[RPFdat$gene_symbol %in% Ngenes,], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 2, colour="black", fill=farbe1) +
  geom_text_repel(data=RPFdat[RPFdat$gene_symbol %in% Agenes,], aes(label = gene_symbol),size = 3) +
  ggtitle("RF")

RPFmalab

pdf("MAplot_RPF_lab.pdf", width = 1.5, height = 1.8)
RPFmalab
dev.off()

```


# target bar
```{r targetbar}
#RNA
RNAdat$target <- "Non-target"
RNAdat$target[sub("\\..*", "", RNAdat$Gene) %in% largetframe$geneID] <- "Target"

RNAtbaru <- as.data.frame(table(RNAdat[RNAdat$padj <= 0.05 & RNAdat$log2FoldChange > 0, "target"]))
RNAtbaru$y <- "RNAseq up"
RNAtbaru$Freq <- RNAtbaru$Freq/sum(RNAtbaru$Freq)

RNAtbard <- as.data.frame(table(RNAdat[RNAdat$padj <= 0.05 & RNAdat$log2FoldChange < 0, "target"]))
RNAtbard$y <- "RNAseq down"
RNAtbard$Freq <- RNAtbard$Freq/sum(RNAtbard$Freq)

#RPF
RPFdat$target <- "Non-target"
RPFdat$target[sub("\\..*", "", RPFdat$Gene) %in% largetframe$geneID] <- "Target"

RPFtbaru <- as.data.frame(table(RPFdat[RPFdat$padj <= 0.05 & RPFdat$log2FoldChange > 0, "target"]))
RPFtbaru$y <- "RPFseq up"
RPFtbaru$Freq <- RPFtbaru$Freq/sum(RPFtbaru$Freq)

RPFtbard <- as.data.frame(table(RPFdat[RPFdat$padj <= 0.05 & RPFdat$log2FoldChange < 0, "target"]))
RPFtbard$y <- "RPFseq down"
RPFtbard$Freq <- RPFtbard$Freq/sum(RPFtbard$Freq)

#combine
ribbar <- rbind(RNAtbaru,RNAtbard, RPFtbaru, RPFtbard)


ribtbarp <- ggplot(ribbar, aes(x=y, y=Freq, fill=Var1)) + geom_bar(stat = "identity", position = "stack") +
  theme_paper()

ribtbarp

#export
pdf("RPFandRNA_tbar.pdf", width = 1, height = 2)
ribtbarp
dev.off()

```

# Session info
```{r sessioninfo}
sessionInfo()
```
