---
title: "TE_plots"
author:
- name: Nikita Verheyden
  affiliation: JLU Giessen
  date: "`r Sys.Date()`"
output:
  BiocStyle::html_document:
      toc: TRUE
      toc_float: TRUE
      code_folding: hide

header-includes:
- \makeatletter\renewcommand*{\fps@figure}{h}\makeatother
- \usepackage{placeins}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Setup

dir
```{r dir}
setwd("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/04_TE_plots")
```


## packages 
```{r packages}

source("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/themes/theme_paper.R")
library(readxl)
library(ggplot2)
library(ggrastr)
library(dplyr)
library(MASS)
library(ggpubr)
library(ggrepel)
```

## data
```{r data}
#Ribo profiling
RNA <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/01_Ribosome_profiling_pipeline/RNA_masterframe.csv")
RPF <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/01_Ribosome_profiling_pipeline/RPF_masterframe.csv")

#Translational efficiency
TEframe <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/deltaTE/TE_m23_genesInRNAandRPF.csv")
head(TEframe)

#targets
larget <- readRDS("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure2/02_compare_miR_enriched_to_Ago_binding_sites/mir181_bs.rds")
largetframe <- as.data.frame(larget)
table(largetframe$set)
largetframe <- largetframe[!(largetframe$set == "ago_bs_mir181_chi"),]
```
## colours
```{r colours}
#colours
farbeneg <- "#b4b4b4"
farbe1 <- "#0073C2FF"
farbe2 <- "#EFC000FF"
farbe3 <- "#CD534CFF"
farbe4 <- "#7AA6DCFF"
farbe5 <- "#868686FF"
farbe6 <- "#003C67FF"
farbe7 <- "#8F7700FF"
farbe8 <- "#3B3B3BFF"
farbe9 <- "#A73030FF"
farbe10 <- "#4A6990FF"
farbe11 <- "#FF6F00FF"
farbe12 <- "#C71000FF"
farbe13 <- "#008EA0FF"
farbe14 <- "#8A4198FF"
farbe15 <- "#5A9599FF"
farbe16 <- "#FF6348FF"
  
RNApcol <- "#b56504"
RNAncol <- "#027d73"
RPFpcol <- "#c4c404"
RPFncol <- "#8d0391"
```




# genelist and cutoffs
```{r genelist}
Agenes <- c("Cd69", "Dusp6", "Ptpn22", "Zfp36l1", "Zfp36l2")
Ogenes <- c("Cd69", "Dusp6", "Ptpn22")
Ngenes <- c("Zfp36l1", "Zfp36l2")

#cutoffs
pms <- 0.05
lfccutoffmax <- 2
```



# TE crossover
```{r tecross}
names(RNA)[4] <- "RNA_log2FoldChange"
names(RPF)[4] <- "RPF_log2FoldChange"

ribo <- left_join(RPF[!is.na(RPF$gene_symbol),], RNA[!is.na(RNA$gene_symbol),], by="Gene")

#density function
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}



#implement density
ribo$density <- get_density(ribo$RNA_log2FoldChange, ribo$RPF_log2FoldChange, n=100)

#colour brewer


#plot
riboplot <- ggplot(ribo, aes(x=RNA_log2FoldChange, y=RPF_log2FoldChange, colour=log2(density))) +
  geom_point_rast(size=0.5) +
  geom_abline(slope = 1, colour=farbe1) +
  geom_hline(yintercept = 0, linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  stat_cor(method = "pearson", label.x = -2, label.y = 2) +
  coord_cartesian(ylim = c(-3,3), xlim = c(-3,3)) +
  scale_colour_gradient(high=farbe3, low=farbeneg) +
  theme_paper()


riboplot

#export
pdf("Crossdots_TE.pdf", width = 2, height = 2)
riboplot
dev.off()
```



# Te volcano
```{r tevol}
head(TEframe)

telfccutoff <- 2.5

#add significance identifier
TEco <- TEframe
TEco$significance <- "Not significant"
TEco$significance[TEco$padj <= pms & TEco$log2FoldChange > 0] <- "Significant up"
TEco$significance[TEco$padj <= pms & TEco$log2FoldChange < 0] <- "Significant down"



#plot
TEcovolcano <- ggplot(TEco, aes(y=-log10(padj), x=log2FoldChange,  fill=factor(significance, levels = c("Not significant", "Significant up","Significant down")))) + geom_point_rast(shape=21, size=0.5, colour=farbeneg) +
  scale_fill_manual(values=c(farbeneg, "#CD534C", "#E3A09C")) +
  geom_point(data = TEco[TEco$significance == "Significant up",], shape=21, colour="black", fill="#CD534C") +
  geom_point(data = TEco[TEco$significance == "Significant down",], shape=21, colour="black", fill="#E3A09C") +
  geom_hline(yintercept = -log10(pms), linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  coord_cartesian(xlim = c(-telfccutoff, telfccutoff))+
  theme_paper() +
  geom_point(data = TEco[TEco$gene_symbol %in% Ngenes,], shape=21, colour="black", fill=farbe1, size=2) +
  geom_point(data = TEco[TEco$gene_symbol %in% Ogenes,], shape=21, colour="black", fill="#595959", size=2) +
  geom_text_repel(data=TEco[TEco$gene_symbol %in% Agenes,], aes(label = gene_symbol),size = 3) +
  ggtitle("TE")

TEcovolcano


#export
pdf("Volcanoplot_TE.pdf", width = 1.7, height = 1.9)
TEcovolcano
dev.off()

table(TEco$significance)
```



# Session info
```{r sessioninfo}
sessionInfo()
```


