---
title: "fig3 TE and MS plots"
author: "Nikita Verheyden"
date: "2023-05-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# setup

dir
```{r dir}
setwd("D:/Krueger_Lab/Publications/miR181_paper/Figure3")
```

## packages 
```{r packages}
source("D:/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/themes/theme_paper.R")
library(xlsx)
library(ggplot2)
library(ggrastr)
library(dplyr)
library(MASS)
```

## data
```{r data}
#ms
ms <- as.data.frame(read.xlsx("D:/Krueger_Lab/R/ECDF plots/Kreuger_analysis_ms.xlsx", 
                              sheetName = "Analysis"))
#adjust upper case lower case of gene names of MS data:
#function
capFirst <- function(s) {
  paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")
}
ms$Gene.Symbol <- tolower(ms$Gene.Symbol)
ms$Gene.Symbol <- capFirst(ms$Gene.Symbol)
names(ms)[names(ms) == 'Gene.Symbol'] <- 'GeneName'
head(ms$GeneName)

#Ribo profiling
RNA <- read.csv("D:/Krueger_Lab/Publications/miR181_paper/Figure3/RNA_masterframe.csv")
RPF <- read.csv("D:/Krueger_Lab/Publications/miR181_paper/Figure3/RPF_masterframe.csv")

#Translational efficiency
TEframe <- read.csv("D:/Krueger_Lab/Publications/miR181_paper_v07122022/Supporting scipts/deltaTE/TE_m23_genesInRNAandRPF.csv")
head(TEframe)



```
## colours
```{r colours}
#colours
farbeneg <- "#b4b4b4"
farbe1 <- "#0073C2FF"
farbe2 <- "#EFC000FF"
farbe3 <- "#CD534CFF"
farbe4 <- "#7AA6DCFF"
farbe5 <- "#868686FF"
farbe6 <- "#003C67FF"
farbe7 <- "#8F7700FF"
farbe8 <- "#3B3B3BFF"
farbe9 <- "#A73030FF"
farbe10 <- "#4A6990FF"
farbe11 <- "#FF6F00FF"
farbe12 <- "#C71000FF"
farbe13 <- "#008EA0FF"
farbe14 <- "#8A4198FF"
farbe15 <- "#5A9599FF"
farbe16 <- "#FF6348FF"
  
RNApcol <- "#b56504"
RNAncol <- "#027d73"
RPFpcol <- "#c4c404"
RPFncol <- "#8d0391"
```


# ms volcano
```{r msvol}
pms <- 0.05
lfccutoffmax <- 1.5

# #make columns with identifiers
msco <- ms
# msco$lfccutoff <- "in"
# msco$lfccutoff[msco$Log2.FC. > lfccutoffmax] <- "high"
# msco$lfccutoff[msco$Log2.FC. < -lfccutoffmax] <- "low"
# 
# #implement cutoff
# msco$Log2.FC.[msco$Log2.FC. > lfccutoffmax] <- lfccutoffmax
# msco$Log2.FC.[msco$Log2.FC. < -lfccutoffmax] <- -lfccutoffmax



#add significance identifier
msco$significance <- "Not significant"
msco$significance[msco$P.value <= pms & msco$Log2.FC. > 0] <- "Significant up"
msco$significance[msco$P.value <= pms & msco$Log2.FC. < 0] <- "Significant down"



#plot
mscovolcano <- ggplot(msco, aes(y=-log10(P.value), x=Log2.FC.,  fill=factor(significance, levels = c("Not significant", "Significant up","Significant down")))) + geom_point_rast(shape=21, size=0.5, colour=farbeneg) +
  scale_fill_manual(values=c(farbeneg, RPFpcol, RPFncol)) +
  geom_point(data = msco[msco$significance == "Significant up",], shape=21, colour="black", fill=RPFpcol) +
  geom_point(data = msco[msco$significance == "Significant down",], shape=21, colour="black", fill=RPFncol) +
  # geom_point(data=msco[msco$significance == "Significant up" & msco$lfccutoff =="high",], aes(y=-log10(P.value), x=Log2.FC.), shape=23, size = 2, colour="black", fill=RPFpcol) +
  # geom_point(data=msco[msco$significance == "Significant down" & msco$lfccutoff =="low",], aes(y=-log10(P.value), x=Log2.FC.), shape=24, size = 2, colour="black", fill=RPFncol) +
  geom_hline(yintercept = -log10(pms), linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  coord_cartesian(xlim = c(-lfccutoffmax, lfccutoffmax))+
  theme_paper()

mscovolcano


#export
pdf("Volcanoplot_MS.pdf", width = 2, height = 2)
mscovolcano
dev.off()
```

# TE crossover
```{r tecross}
names(RNA)[4] <- "RNA_log2FoldChange"
names(RPF)[4] <- "RPF_log2FoldChange"

ribo <- left_join(RPF[!is.na(RPF$gene_symbol),], RNA[!is.na(RNA$gene_symbol),], by="Gene")

#density function
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}

set.seed(1)
dat <- data.frame(
  x = c(
    rnorm(1e4, mean = 0, sd = 0.1),
    rnorm(1e3, mean = 0, sd = 0.1)
  ),
  y = c(
    rnorm(1e4, mean = 0, sd = 0.1),
    rnorm(1e3, mean = 0.1, sd = 0.2)
  )
)

#implement density
ribo$density <- get_density(ribo$RNA_log2FoldChange, ribo$RPF_log2FoldChange, n=100)

#colour brewer


#plot
riboplot <- ggplot(ribo, aes(x=RNA_log2FoldChange, y=RPF_log2FoldChange, colour=density)) +
  geom_point(size=1) +
  geom_smooth(method=lm, colour=farbe1) +
  geom_hline(yintercept = 0, linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  coord_cartesian(ylim = c(-3,3), xlim = c(-3,3)) +
  scale_color_gradient(low = farbeneg, high = farbe3) +
  theme_paper()


riboplot

#export
pdf("Crossdots_TE.pdf", width = 2, height = 2)
riboplot
dev.off()
```



#Te volcano
```{r tevol}
head(TEframe)

telfccutoff <- 2.5

#add significance identifier
TEco <- TEframe
TEco$significance <- "Not significant"
TEco$significance[TEco$pvalue <= pms & TEco$log2FoldChange > 0] <- "Significant up"
TEco$significance[TEco$pvalue <= pms & TEco$log2FoldChange < 0] <- "Significant down"



#plot
TEcovolcano <- ggplot(TEco, aes(y=-log10(pvalue), x=log2FoldChange,  fill=factor(significance, levels = c("Not significant", "Significant up","Significant down")))) + geom_point_rast(shape=21, size=0.5, colour=farbeneg) +
  scale_fill_manual(values=c(farbeneg, RPFpcol, RPFncol)) +
  geom_point(data = TEco[TEco$significance == "Significant up",], shape=21, colour="black", fill="#CD534C") +
  geom_point(data = TEco[TEco$significance == "Significant down",], shape=21, colour="black", fill="#E3A09C") +
  geom_hline(yintercept = -log10(pms), linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  coord_cartesian(xlim = c(-telfccutoff, telfccutoff))+
  theme_paper()

TEcovolcano


#export
pdf("Volcanoplot_TE.pdf", width = 2, height = 2)
TEcovolcano
dev.off()
```


# Session info
```{r sessioninfo}
sessionInfo()
```



