---
title: "Seedprox_to_BS"
author: "Nikita Verheyden"
date: "2023-05-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

path
```{r path}
setwd("D:/Krueger_Lab/Publications/miR181_paper/Figure2/Seed in relation to BS")
```

## Packages
```{r packages}
source("D:/Krueger_Lab/Publications/miR181_paper_v21022023/Figure_theme/theme_paper.R")
library(ggplot2)
library(dplyr)
library(GenomicRanges)
library(BSgenome.Mmusculus.UCSC.mm10)
library(eulerr)
```

## Data
```{r data}
#new chimeric data
bsTranscript <- readRDS("D:/Krueger_Lab/R/OldvsNew_chimeric_ecdf/BS_with_chimeric_from_181enriched_and_non_enriched.rds")
# sort by type of mirna
table(bsTranscript$mir181)
new181df <- bsTranscript[bsTranscript$mir181==TRUE,] 

#why is this not the same?
load(file = "D:/Krueger_Lab/Publications/miR181_paper_v07122022/Figure_1/chimbsGene.rda")



#load target from miR-eCLIP
WT181 <- read.csv("D:/Krueger_Lab/miReCLIP/peak_info_enriched181_WT.csv")
#for now only keep 5'UTRs, CDS and 3'UTRs
WT181sel <- WT181[WT181$Feature %in% c("3' UTR", "CDS", "5' UTR"),]

# remove commas
WT181sel$Start <- gsub(",", "" ,WT181sel$Start) 
WT181sel$End <- gsub(",", "" ,WT181sel$End) 

head(WT181sel)
```

colour pattern
```{r colours}
#colours
farbeneg <- "#b4b4b4"
farbe1 <- "#0073C2FF"
farbe2 <- "#EFC000FF"
farbe3 <- "#CD534CFF"
farbe4 <- "#7AA6DCFF"
farbe5 <- "#868686FF"
farbe6 <- "#003C67FF"
farbe7 <- "#8F7700FF"
farbe8 <- "#3B3B3BFF"
farbe9 <- "#A73030FF"
farbe10 <- "#4A6990FF"
farbe11 <- "#FF6F00FF"
farbe12 <- "#C71000FF"
farbe13 <- "#008EA0FF"
farbe14 <- "#8A4198FF"
farbe15 <- "#5A9599FF"
farbe16 <- "#FF6348FF"
  
RNApcol <- "#b56504"
RNAncol <- "#027d73"
RPFpcol <- "#c4c404"
RPFncol <- "#8d0391"
```

# Data procession

## Make into Granges objects
```{r Granges}
new181range <- makeGRangesFromDataFrame(new181df, keep.extra.columns = T)

old181range <- makeGRangesFromDataFrame(WT181sel, keep.extra.columns = T)


new181range

old181range
```

```{r seedpositions}
#old
# Sequence around chimeric mir181 BS
BS_mir181_chimera_200ntold <- old181range + 100
BS_mir181_chimera_200nt_seqold <- getSeq(BS_mir181_chimera_200ntold, x = BSgenome.Mmusculus.UCSC.mm10) %>% RNAStringSet()

Seedold <- vmatchPattern(pattern = "GAAUGU", BS_mir181_chimera_200nt_seqold) %>% unlist()

seed_ggold <- data.frame(position_GAAUGU = start(Seedold))

seed_ggold=seed_ggold-100


#new
# Sequence around chimeric mir181 BS
BS_mir181_chimera_200ntnew <- new181range + 100
BS_mir181_chimera_200nt_seqnew <- getSeq(BS_mir181_chimera_200ntnew, x = BSgenome.Mmusculus.UCSC.mm10) %>% RNAStringSet()

Seednew <- vmatchPattern(pattern = "GAAUGU", BS_mir181_chimera_200nt_seqnew) %>% unlist()

seed_ggnew <- data.frame(position_GAAUGU = start(Seednew))

seed_ggnew=seed_ggnew-100
```

# PLot

```{r seed_plot}
# old
seedplotold <- ggplot(seed_ggold, aes(x = position_GAAUGU))+
  geom_density(colour="black" , fill=farbe2) +
  geom_rect(aes(xmin=-3.5, xmax=3.5, ymin=0, ymax=Inf), fill = farbe1)+
  scale_x_continuous("Position of Seed", expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 0.025))+
  theme_bw() +
  theme_paper() +
  ggtitle("Seed relative to binding site")

seedplotold


# new
seedplotnew <- ggplot(seed_ggnew, aes(x = position_GAAUGU))+
  geom_density(colour="black" , fill=farbe2) +
  geom_rect(aes(xmin=-3.5, xmax=3.5, ymin=0, ymax=Inf), fill = farbe1)+
  scale_x_continuous("Position of Seed", expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 0.025))+
  theme_bw() +
  theme_paper() +
  ggtitle("Seed relative to binding site")

seedplotnew

pdf("Seedplot_eclipse_targets.pdf", height = 3, width = 6)
seedplotold
dev.off()

pdf("Seedplot_Melina_targets_with_chimread.pdf", height = 3, width = 6)
seedplotnew
dev.off()
```
## Seed site plot
try to implement melinas script
```{r seed_plot_chimreads}
# Sequence around chimeric mir181 BS
BS_mir181_chimera_200nt <- bsGene[bsGene$type == "WT_181",] + 100
BS_mir181_chimera_200nt_seq <- getSeq(BS_mir181_chimera_200nt, x = BSgenome.Mmusculus.UCSC.mm10) %>% RNAStringSet()

Seed <- vmatchPattern(pattern = "GAAUGU", BS_mir181_chimera_200nt_seq) %>% unlist()

seed_gg <- data.frame(position_GAAUGU = start(Seed))

seed_gg=seed_gg-100

seedplot <- ggplot(seed_gg, aes(x = position_GAAUGU))+
  geom_density(colour="black" , fill=farbe2) +
  geom_rect(aes(xmin=-3.5, xmax=3.5, ymin=0, ymax=Inf), fill = farbe1)+
  scale_x_continuous("Position of Seed", expand = c(0,0)) +
  scale_y_continuous(expand = c(0,0), limits = c(0, 0.025))+
  theme_bw() + 
  theme_paper() +
  ggtitle("Seed relative to binding site")

seedplot


pdf("Seedplot_Melina_just_chimreads.pdf", height = 3, width = 6)
seedplot
dev.off()

```
# compare other data from just chimeric sites and mirco bs with chimeric
```{r compare}
oldnew <- as.data.frame(bsGene[bsGene$type == "WT_181", "geneName"])
newnew <- as.data.frame(new181range[, "geneName"])

ollist <- list(oldnew[!duplicated(oldnew$geneName), "geneName"], newnew[!duplicated(newnew$geneName), "geneName"])
names(ollist) <- c("All chimeric", "BS with chimeric read")

plot(euler(ollist, shape="ellipse"), quantities = T, fills=c(farbe1, farbe2), main = "Old vs ne chimeric miR-181 enriched binding sites")



```

# Session info
```{r session info}
sessionInfo()
```
