---
title: "fig3 TE and MS plots"
author: "Nikita Verheyden"
date: "2023-05-23"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# setup

dir
```{r dir}
setwd("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3")
```

## packages 
```{r packages}
source("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/themes/theme_paper.R")
library(readxl)
library(ggplot2)
library(ggrastr)
library(dplyr)
library(MASS)
library(ggpubr)
library(ggrepel)
```

## data
```{r data}
#ms
ms <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure2/MS_data_MMU_02082023.csv")

#Ribo profiling
RNA <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/RNA_masterframe.csv")
RPF <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/RPF_masterframe.csv")

#Translational efficiency
TEframe <- read.csv("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/deltaTE/TE_m23_genesInRNAandRPF.csv")
head(TEframe)

#targets
larget <- readRDS("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3/mir181_bs_afterFigure2B.rds")
largetframe <- as.data.frame(larget)
table(largetframe$set)
largetframe <- largetframe[!(largetframe$set == "ago_bs_mir181_chi"),]

```
## colours
```{r colours}
#colours
farbeneg <- "#b4b4b4"
farbe1 <- "#0073C2FF"
farbe2 <- "#EFC000FF"
farbe3 <- "#CD534CFF"
farbe4 <- "#7AA6DCFF"
farbe5 <- "#868686FF"
farbe6 <- "#003C67FF"
farbe7 <- "#8F7700FF"
farbe8 <- "#3B3B3BFF"
farbe9 <- "#A73030FF"
farbe10 <- "#4A6990FF"
farbe11 <- "#FF6F00FF"
farbe12 <- "#C71000FF"
farbe13 <- "#008EA0FF"
farbe14 <- "#8A4198FF"
farbe15 <- "#5A9599FF"
farbe16 <- "#FF6348FF"
  
RNApcol <- "#b56504"
RNAncol <- "#027d73"
RPFpcol <- "#c4c404"
RPFncol <- "#8d0391"
```


# genelist
```{r genelist}
Agenes <- c("Cd69", "Dusp6", "Ptpn22", "Zfp36l1", "Zfp36l2")
Ogenes <- c("Cd69", "Dusp6", "Ptpn22")
Ngenes <- c("Zfp36l1", "Zfp36l2")
```


# MA plots with labels
```{r plotslab}
ylim <- 2
xlim <- 10^6
xmin <- 10

lfcsig <- 0
pvsig <- 0.05

#RNA
RNA$LFCandPADJSig <- "Not significant"
RNA$LFCandPADJSig[RNA$padj <= pvsig & RNA$log2FoldChange >= lfcsig] <- "Significant up"
RNA$LFCandPADJSig[RNA$padj <= pvsig & RNA$log2FoldChange <= -lfcsig] <- "Significant down"

#make columns with identifiers
RNAdat <- RNA[RNA$baseMean >= xmin,]
RNAdat$ycutoff <- "in"
RNAdat$ycutoff[RNAdat$log2FoldChange > ylim] <- "high"
RNAdat$ycutoff[RNAdat$log2FoldChange < -ylim] <- "low"

RNAdat$xcutoff <- "in"
RNAdat$xcutoff[RNAdat$baseMean > xlim] <- "high"

#implement cutoff
RNAdat$log2FoldChange[RNAdat$log2FoldChange > ylim] <- ylim
RNAdat$log2FoldChange[RNAdat$log2FoldChange < -ylim] <- -ylim
RNAdat$baseMean[RNAdat$baseMean > xlim] <- xlim


#RPF
RPF$LFCandPADJSig <- "Not significant"
RPF$LFCandPADJSig[RPF$padj <= pvsig & RPF$log2FoldChange >= lfcsig] <- "Significant up"
RPF$LFCandPADJSig[RPF$padj <= pvsig & RPF$log2FoldChange <= -lfcsig] <- "Significant down"


#make columns with identifiers
RPFdat <- RPF[RPF$baseMean >= xmin,]
RPFdat$ycutoff <- "in"
RPFdat$ycutoff[RPFdat$log2FoldChange > ylim] <- "high"
RPFdat$ycutoff[RPFdat$log2FoldChange < -ylim] <- "low"

RPFdat$xcutoff <- "in"
RPFdat$xcutoff[RPFdat$baseMean > xlim] <- "high"

#implement cutoff
RPFdat$log2FoldChange[RPFdat$log2FoldChange > ylim] <- ylim
RPFdat$log2FoldChange[RPFdat$log2FoldChange < -ylim] <- -ylim
RPFdat$baseMean[RPFdat$baseMean > xlim] <- xlim


#RNA
RNAmalab <- ggplot(RNAdat[!(RNAdat$xcutoff == "high"),], aes(y=log2FoldChange, x=log10(baseMean))) + geom_point_rast(shape=21, size = 0.5, 
     aes(fill = factor(LFCandPADJSig), colour=factor(LFCandPADJSig))) +
  scale_fill_manual(values = c(farbeneg, RNAncol, RNApcol)) + scale_colour_manual(values = c(farbeneg, "black", "black")) +
  geom_point(data=RNAdat[RNAdat$LFCandPADJSig == "Significant down" & RNAdat$ycutoff =="in" & RNAdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 1, colour="black", fill=RNAncol) +
  geom_point(data=RNAdat[RNAdat$LFCandPADJSig == "Significant up" & RNAdat$ycutoff =="in" & RNAdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 1, colour="black", fill=RNApcol) +
  geom_point(data=RNAdat[RNAdat$LFCandPADJSig == "Significant up" & RNAdat$ycutoff =="high" & RNAdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=24, size = 1, colour="black", fill=RNApcol) +
  geom_point(data=RNAdat[RNAdat$LFCandPADJSig == "Significant down" & RNAdat$ycutoff =="low" & RNAdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=25, size = 1, colour="black", fill=RNAncol) +
  theme_paper() +
  geom_point(data=RNAdat[RNAdat$xcutoff == "high",], aes(y=log2FoldChange, x=log10(baseMean)), shape="\u25BA", size = 3, colour=farbeneg) +
  geom_hline(yintercept = 0, linetype="solid", colour="black") + 
  geom_hline(yintercept = lfcsig, linetype="dashed", colour="black") + 
  geom_hline(yintercept = -lfcsig, linetype="dashed", colour="black") + 
  scale_y_continuous("Fold change miR-181a/b-1 KO/WT (log2)", limits = c(-ylim, ylim)) + scale_x_continuous("Base mean expression ratio (log10)", limits = c(log10(xmin), log10(xlim))) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  geom_point(data=RNAdat[RNAdat$gene_symbol %in% Ogenes,], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 2, colour="black", fill="#595959") +
  geom_point(data=RNAdat[RNAdat$gene_symbol %in% Ngenes,], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 2, colour="black", fill=farbe1) +
  geom_text_repel(data=RNAdat[RNAdat$gene_symbol %in% Agenes,], aes(label = gene_symbol),size = 3)

RNAmalab

pdf("MAplot_RNA_lab.pdf", width = 1.8, height = 1.8)
RNAmalab
dev.off()



#RPF
RPFmalab <- ggplot(RPFdat[!(RPFdat$xcutoff == "high"),], aes(y=log2FoldChange, x=log10(baseMean))) + geom_point_rast(shape=21, size = 0.5, 
     aes(fill = factor(LFCandPADJSig), colour=factor(LFCandPADJSig))) +
  scale_fill_manual(values = c(farbeneg, RNAncol, RNApcol)) + scale_colour_manual(values = c(farbeneg, "black", "black")) +
  geom_point(data=RPFdat[RPFdat$LFCandPADJSig == "Significant down" & RPFdat$ycutoff =="in" & RPFdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 1, colour="black", fill=RNAncol) +
  geom_point(data=RPFdat[RPFdat$LFCandPADJSig == "Significant up" & RPFdat$ycutoff =="in" & RPFdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 1, colour="black", fill=RNApcol) +
  geom_point(data=RPFdat[RPFdat$LFCandPADJSig == "Significant up" & RPFdat$ycutoff =="high" & RPFdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=24, size = 1, colour="black", fill=RNApcol) +
  geom_point(data=RPFdat[RPFdat$LFCandPADJSig == "Significant down" & RPFdat$ycutoff =="low" & RPFdat$xcutoff == "in",], aes(y=log2FoldChange, x=log10(baseMean)), shape=25, size = 1, colour="black", fill=RNAncol) +
  theme_paper() +
  geom_point(data=RPFdat[RPFdat$xcutoff == "high",], aes(y=log2FoldChange, x=log10(baseMean)), shape="\u25BA", size = 3, colour=farbeneg) +
  geom_hline(yintercept = 0, linetype="solid", colour="black") + 
  geom_hline(yintercept = lfcsig, linetype="dashed", colour="black") + 
  geom_hline(yintercept = -lfcsig, linetype="dashed", colour="black") + 
  scale_y_continuous("Fold change miR-181a/b-1 KO/WT (log2)", limits = c(-ylim, ylim)) + scale_x_continuous("Base mean expression ratio (log10)", limits = c(log10(xmin), log10(xlim))) +
  guides(color = guide_legend(override.aes = list(size = 3))) +
  geom_point(data=RPFdat[RPFdat$gene_symbol %in% Ogenes,], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 2, colour="black", fill="#595959") +
  geom_point(data=RPFdat[RPFdat$gene_symbol %in% Ngenes,], aes(y=log2FoldChange, x=log10(baseMean)), shape=21, size = 2, colour="black", fill=farbe1) +
  geom_text_repel(data=RPFdat[RPFdat$gene_symbol %in% Agenes,], aes(label = gene_symbol),size = 3)

RPFmalab

pdf("MAplot_RPF_lab.pdf", width = 1.8, height = 1.8)
RPFmalab
dev.off()

```


# ms volcano
```{r msvol}
pms <- 0.05
lfccutoffmax <- 2.5

# #make columns with identifiers
msco <- ms
# msco$lfccutoff <- "in"
# msco$lfccutoff[msco$log2FoldChange > lfccutoffmax] <- "high"
# msco$lfccutoff[msco$log2FoldChange < -lfccutoffmax] <- "low"
# 
# #implement cutoff
# msco$log2FoldChange[msco$log2FoldChange > lfccutoffmax] <- lfccutoffmax
# msco$log2FoldChange[msco$log2FoldChange < -lfccutoffmax] <- -lfccutoffmax



#add significance identifier
msco$significance <- "Not significant"
msco$significance[msco$padj <= pms & msco$log2FoldChange > 0] <- "Significant up"
msco$significance[msco$padj <= pms & msco$log2FoldChange < 0] <- "Significant down"

msco[order(msco$padj),]

#plot
mscovolcano <- ggplot(msco, aes(y=-log10(padj), x=log2FoldChange,  fill=factor(significance, levels = c("Not significant", "Significant up","Significant down")))) + geom_point_rast(shape=21, size=0.5, colour=farbeneg) +
  scale_fill_manual(values=c(farbeneg, RPFpcol, RPFncol)) +
  geom_point(data = msco[msco$significance == "Significant up",], shape=21, colour="black", fill=RPFpcol) +
  geom_point(data = msco[msco$significance == "Significant down",], shape=21, colour="black", fill=RPFncol) +
  # geom_point(data=msco[msco$significance == "Significant up" & msco$lfccutoff =="high",], aes(y=-log10(padj), x=log2FoldChange), shape=23, size = 2, colour="black", fill=RPFpcol) +
  # geom_point(data=msco[msco$significance == "Significant down" & msco$lfccutoff =="low",], aes(y=-log10(padj), x=log2FoldChange), shape=24, size = 2, colour="black", fill=RPFncol) +
  geom_hline(yintercept = -log10(pms), linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  coord_cartesian(xlim = c(-lfccutoffmax, lfccutoffmax))+
  theme_paper()

mscovolcano


#export
pdf("Volcanoplot_MS.pdf", width = 2, height = 2)
mscovolcano
dev.off()
```

## MS Barplots
```{r MSbarplots}
msbardat <- data.frame(c("Significantly_up", "Significantly_down"),
                        c(length(ms[ms$log2FoldChange > 0 & ms$padj <= 0.05 & !is.na(ms$padj),"gene_symbol"]), -length(ms[ms$log2FoldChange < 0 & ms$padj <= 0.05 & !is.na(ms$padj),"gene_symbol"])))
colnames(msbardat)=c("ID", "Number_of_genes")


msbar <- ggplot(data=msbardat, aes(x=ID, y=Number_of_genes, fill=ID)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = c(RPFncol, RPFpcol)) +
  theme_paper() + 
  theme(legend.position = "None")
  

msbar

# export
pdf("MSbarplot.pdf", width=1, height = 2)
msbar
dev.off()

```

# TE crossover
```{r tecross}
names(RNA)[4] <- "RNA_log2FoldChange"
names(RPF)[4] <- "RPF_log2FoldChange"

ribo <- left_join(RPF[!is.na(RPF$gene_symbol),], RNA[!is.na(RNA$gene_symbol),], by="Gene")

#density function
get_density <- function(x, y, ...) {
  dens <- MASS::kde2d(x, y, ...)
  ix <- findInterval(x, dens$x)
  iy <- findInterval(y, dens$y)
  ii <- cbind(ix, iy)
  return(dens$z[ii])
}



#implement density
ribo$density <- get_density(ribo$RNA_log2FoldChange, ribo$RPF_log2FoldChange, n=100)

#colour brewer


#plot
riboplot <- ggplot(ribo, aes(x=RNA_log2FoldChange, y=RPF_log2FoldChange, colour=log2(density))) +
  geom_point_rast(size=0.5) +
  geom_abline(slope = 1, colour=farbe1) +
  geom_hline(yintercept = 0, linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  stat_cor(method = "pearson", label.x = -2, label.y = 2) +
  coord_cartesian(ylim = c(-3,3), xlim = c(-3,3)) +
  scale_colour_gradient(high=farbe3, low=farbeneg) +
  theme_paper()


riboplot

#export
pdf("Crossdots_TE.pdf", width = 2, height = 2)
riboplot
dev.off()
```



# Te volcano
```{r tevol}
head(TEframe)

telfccutoff <- 2.5

#add significance identifier
TEco <- TEframe
TEco$significance <- "Not significant"
TEco$significance[TEco$pvalue <= pms & TEco$log2FoldChange > 0] <- "Significant up"
TEco$significance[TEco$pvalue <= pms & TEco$log2FoldChange < 0] <- "Significant down"



#plot
TEcovolcano <- ggplot(TEco, aes(y=-log10(pvalue), x=log2FoldChange,  fill=factor(significance, levels = c("Not significant", "Significant up","Significant down")))) + geom_point_rast(shape=21, size=0.5, colour=farbeneg) +
  scale_fill_manual(values=c(farbeneg, "#CD534C", "#E3A09C")) +
  geom_point(data = TEco[TEco$significance == "Significant up",], shape=21, colour="black", fill="#CD534C") +
  geom_point(data = TEco[TEco$significance == "Significant down",], shape=21, colour="black", fill="#E3A09C") +
  geom_hline(yintercept = -log10(pms), linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  coord_cartesian(xlim = c(-telfccutoff, telfccutoff))+
  theme_paper()

TEcovolcano


#export
pdf("Volcanoplot_TE.pdf", width = 2, height = 2)
TEcovolcano
dev.off()
```


## TE barplots
```{r tebarplots}
tebar <- ggplot(data = TEco[!(TEco$significance == "Not significant"),], aes(x=significance, fill=significance)) + 
  geom_bar() +
  scale_fill_manual(values = c("#E3A09C", "#CD534C")) +
  theme_paper() +
  theme(legend.position = "None")
  

tebar

# export
pdf("TEbarplot.pdf", width=1, height = 2)
tebar
dev.off()
```


# RPF vs MS
```{r RPFvsMS}
names(ms)[40] <- "MS_log2FoldChange"
names(ms)[24] <- "gene_symbol"

msribo <- inner_join(RPF[!is.na(RPF$gene_symbol),], ms[!is.na(ms$gene_symbol),], by="gene_symbol")


#implement density
msribo$density <- get_density(msribo$MS_log2FoldChange, msribo$RPF_log2FoldChange, n=100)

#colour brewer


#plot
msriboplot <- ggplot(msribo, aes(x=MS_log2FoldChange, y=RPF_log2FoldChange, colour=log2(density))) +
  geom_point_rast(size=0.5) +
  geom_abline(slope = 1, colour=farbe1) +
  geom_hline(yintercept = 0, linetype="dashed") +
  geom_vline(xintercept = 0, linetype="dashed") +
  stat_cor(method = "pearson", label.x = -1, label.y = 1) +
  scale_colour_gradient(low=farbeneg, high=farbe3) +
  theme_paper() +
  coord_cartesian(xlim = c(-1,1), ylim = c(-1,1))


msriboplot

#export
pdf("Crossdots_MSvsRPF.pdf", width = 2, height = 2)
msriboplot
dev.off()
```



# RNA and RPF bar plots

## RNA
```{r RNAbarplot}
RNAbardat <- data.frame(c("Significantly_up", "Significantly_down"),
                        c(length(RNA[RNA$RNA_log2FoldChange > 0 & RNA$padj <= 0.05,"gene_symbol"]), -length(RNA[RNA$RNA_log2FoldChange < 0 & RNA$padj <= 0.05,"gene_symbol"])))
colnames(RNAbardat)=c("ID", "Number_of_genes")

RNAbar <- ggplot(data=RNAbardat, aes(x=ID, y=Number_of_genes, fill=ID)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = c(RNAncol, RNApcol)) +
  theme_paper() + 
  theme(legend.position = "None")

RNAbar

# export
pdf("RNAbarplot.pdf", width=1, height = 2)
RNAbar
dev.off()

table(RNAbardat)
```


## RPF
```{r RPFbarplot}
RPFbardat <- data.frame(c("Significantly_up", "Significantly_down"),
                        c(length(RPF[RPF$RPF_log2FoldChange > 0 & RPF$padj <= 0.05,"gene_symbol"]), -length(RPF[RPF$RPF_log2FoldChange < 0 & RPF$padj <= 0.05,"gene_symbol"])))
colnames(RPFbardat)=c("ID", "Number_of_genes")

RPFbar <- ggplot(data=RPFbardat, aes(x=ID, y=Number_of_genes, fill=ID)) +
  geom_bar(stat = "identity") +
  geom_hline(yintercept = 0) +
  scale_fill_manual(values = c(RNAncol, RNApcol)) +
  theme_paper() + 
  theme(legend.position = "None")

RPFbar

# export
pdf("RPFbarplot.pdf", width=1, height = 2)
RPFbar
dev.off()

table(RPFbardat)
```



# Session info
```{r sessioninfo}
sessionInfo()
```



