---
title: "Fig3_ECDF_plots"
author: "Nikita Verheyden"
date: "2023-04-03"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Setup

```{r directory}
setwd("D:/Krueger_Lab/Publications/miR181_paper/Figure3")
```

```{r packages}
source("D:/Krueger_Lab/Publications/miR181_paper_v21022023/Figure_theme/theme_paper.R")
library(ggplot2)
library(dplyr)
library(readxl)
```


```{r data}
#Ribo data
RPF <- read.csv("D:/Krueger_Lab/Publications/miR181_paper/Figure3/RPF_masterframe.csv")
#RNA data
RNA <- read.csv("D:/Krueger_Lab/Publications/miR181_paper/Figure3/RNA_masterframe.csv")

#MS data
ms <- as.data.frame(read_xlsx("D:/Krueger_Lab/R/ECDF plots/Kreuger_analysis_ms.xlsx", 
                              sheet = "Analysis"))
#adjust upper case lower case of gene names of MS data:
#function
capFirst <- function(s) {
  paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")
}
ms$`Gene Symbol` <- tolower(ms$`Gene Symbol`)
ms$`Gene Symbol` <- capFirst(ms$`Gene Symbol`)
names(ms)[names(ms) == 'Gene Symbol'] <- 'GeneName'
head(ms$GeneName)
#TE data
TEframe <- read.csv("D:/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/deltaTE/TE_m23_genesInRNAandRPF.csv")
head(TEframe)


#Targetdata
#this is still the old data, change later!!!!
bsTranscript <- readRDS("D:/Krueger_Lab/R/OldvsNew_chimeric_ecdf/BS_with_chimeric_from_181enriched_and_non_enriched.rds")
# sort by type of mirna
table(bsTranscript$mir181)
#using only miR-181 and removing introns
new181df <- bsTranscript[bsTranscript$mir181==TRUE & !(bsTranscript$region == "intron"),] 

```
Introns were removed in this dataset!


## colour pattern
```{r colours}
#colours
farbeneg <- "#b4b4b4"
farbe1 <- "#0073C2FF"
farbe2 <- "#EFC000FF"
farbe3 <- "#CD534CFF"
farbe4 <- "#7AA6DCFF"
farbe5 <- "#868686FF"
farbe6 <- "#003C67FF"
farbe7 <- "#8F7700FF"
farbe8 <- "#3B3B3BFF"
farbe9 <- "#A73030FF"
farbe10 <- "#4A6990FF"
farbe11 <- "#FF6F00FF"
farbe12 <- "#C71000FF"
farbe13 <- "#008EA0FF"
farbe14 <- "#8A4198FF"
farbe15 <- "#5A9599FF"
farbe16 <- "#FF6348FF"
  
RNApcol <- "#b56504"
RNAncol <- "#027d73"
RPFpcol <- "#c4c404"
RPFncol <- "#8d0391"
```



# inspect data
```{r inspect}
head(RPF)

head(new181df)
```

# split by number of MRE

## process data
```{r numdat}
#get number
numtarg <- as.data.frame(table(new181df$geneID))
colnames(numtarg) = c("Gene", "MRE_number")

#apply to RPF
numdatRPF <- left_join(RPF, numtarg, by="Gene")
numdatRPF$MRE_number[is.na(numdatRPF$MRE_number)] <- 0
##additional numidcolumn
numdatRPF$MRE_num_cat <- ifelse(numdatRPF$MRE_number == 0, "Non-target",
                                ifelse(numdatRPF$MRE_number == 1, "1 MRE",
                                       ifelse(numdatRPF$MRE_number == 2, "2 MREs", "3+ MREs")))


#apply to RNA
numdatRNA <- left_join(RNA, numtarg, by="Gene")
numdatRNA$MRE_number[is.na(numdatRNA$MRE_number)] <- 0
##additional numidcolumn
numdatRNA$MRE_num_cat <- ifelse(numdatRNA$MRE_number == 0, "Non-target",
                                ifelse(numdatRNA$MRE_number == 1, "1 MRE",
                                       ifelse(numdatRNA$MRE_number == 2, "2 MREs", "3+ MREs")))
```

RPF
```{r headnumRPF}
head(numdatRPF)
```
RNA
```{r headnumRNA}
head(numdatRNA)
```

## plot
```{r numplot}
#RPF
RPFnumplot = ggplot(numdatRPF, aes(log2FoldChange, colour=factor(MRE_num_cat, 
                                                                 levels = c("Non-target", "1 MRE", "2 MREs", "3+ MREs")))) + 
  stat_ecdf(geom = "step", linewidth=1) +
  coord_cartesian(xlim = c(-0.8, 0.8)) +
  scale_colour_manual(values = c("black", farbe1, farbe2, farbe3)) +
  theme_bw() +
  theme(legend.title = element_blank())
#RNA
RNAnumplot = ggplot(numdatRNA, aes(log2FoldChange, colour=factor(MRE_num_cat, 
                                                                 levels = c("Non-target", "1 MRE", "2 MREs", "3+ MREs")))) + 
  stat_ecdf(geom = "step", linewidth=1) +
  coord_cartesian(xlim = c(-0.8, 0.8)) +
  scale_colour_manual(values = c("black", farbe1, farbe2, farbe3)) +
  theme_bw() +
  theme(legend.title = element_blank())
```

RPF
```{r numplotRPF}
RPFnumplot
```
RNA
```{r numplotRNA}
RNAnumplot
```

# split by type of MRE

## process data
```{r typedat}
head(new181df)
```

## plot
```{r typeplot}




```

# split by position of MRE

## process data
```{r posdat}
posdat <- new181df[, c("geneID", "region")]
colnames(posdat) <- c("Gene", "region")

posRPF <- left_join(RPF, posdat, by="Gene")
posRPF$region[is.na(posRPF$region)] <- "Non-target"

posRNA <- left_join(RNA, posdat, by="Gene")
posRNA$region[is.na(posRNA$region)] <- "Non-target"

```
RPF
```{r posdatRPF}
head(posRPF)
```
RNA
```{r posdatRNA}
head(posRNA)
```

## plot
```{r posplot}
#RPF
RPFposplot = ggplot(posRPF, aes(log2FoldChange, colour=factor(region, 
                                                                 levels = c("Non-target", "utr5", "cds", "utr3")))) + 
  stat_ecdf(geom = "step", linewidth=1) +
  coord_cartesian(xlim = c(-0.8, 0.8)) +
  scale_colour_manual(values = c("black", farbe1, farbe2, farbe3)) +
  theme_bw() +
  theme(legend.title = element_blank())
```

RPF
```{r posplotRPF}
RPFposplot
```

RNA
```{r posplotRNA}
RNAposplot
```

# Session info
```{r session_info}
sessionInfo()

```




