---
title: "Genome Tracks fig S2"
author: "Nikita Verheyden"
output: pdf_document
date: "2023-07-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Setup

```{r}
setwd("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Figure3")
```


## load packages
```{r packages}
source("C:/Users/nikit/Documents/Krueger_Lab/Publications/miR181_paper/Supporting_scripts/themes/theme_paper.R")
library(Gviz)


```


## load data
```{r data}



```



# Make gviz plot for RPF vs RNAseq

```{r gviz}
scoord = 80108008 
ecoord = 80108895
tchr = "chr12"
clim = 45

gatrack <- GenomeAxisTrack()



#KO minus
KOm <- as.data.frame(IPKOminus)
KOm <- KOm[KOm$seqnames == tchr & KOm$start >= scoord & KOm$end <= ecoord,]
KOm$seqnames <- as.character(KOm$seqnames)
KOm <- makeGRangesFromDataFrame(KOm, keep.extra.columns = T)

KOmT <- DataTrack(KOm, name="KO-", ylim = c(0,clim))


#WT minus
WTm <- as.data.frame(IPWTminus)
WTm <- WTm[WTm$seqnames == tchr & WTm$start >= scoord & WTm$end <= ecoord,]
WTm$seqnames <- as.character(WTm$seqnames)
WTm <- makeGRangesFromDataFrame(WTm, keep.extra.columns = T)

WTmT <- DataTrack(WTm, name="WT-", ylim = c(0,clim))

#181 WT minus
WT181m <- as.data.frame(IP181WTminus)
WT181m <- WT181m[WT181m$seqnames == tchr & WT181m$start >= scoord & WT181m$end <= ecoord,]
WT181m$seqnames <- as.character(WT181m$seqnames)
WT181m <- makeGRangesFromDataFrame(WT181m, keep.extra.columns = T)

WT181mT <- DataTrack(WT181m, name="WT181-", ylim = c(0,clim))




plotTracks(list(WTmT, KOmT,WT181mT, diffresT,  gatrack), from = scoord, to= ecoord, type="histogram", featureAnnotation = "id", 
           fontsize.feature=10, fontcolor.feature = "black")

```


# Session info
```{r}
sessionInfo()
```